### ISSUE TITLE
Error when using -B (--crawlbot) option

### ISSUE THREAD

**Issue by owenmurr** [shirosaidev/diskover#26]
When using the diskover.py with -B option the following error message is returned - 

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/diskover/diskover_crawlbot.py", line 76, in bot_thread
    diskover.crawl_tree(path, cliargs, logger, reindex_dict)
  File "/root/diskover/diskover.py", line 1328, in crawl_tree
    wait_for_worker_bots()
  File "/root/diskover/diskover.py", line 1461, in wait_for_worker_bots
    logger.info('Found %s diskover RQ worker bots', len(workers))
NameError: global name 'logger' is not defined

**Comment by shirosaidev** [comment]
I just pushed some patches to rc10 for crawlbot continuous scanner (-B), please update and let me know if it works for you now.

**Comment by owenmurr** [comment]
Hi, 

I did pull down the new changes this morning, but I'm still getting the same error as above.

Thanks, 

Owen

**Comment by shirosaidev** [comment]
please reply back here your findings with using -B, I haven't had much time to really test that feature out.

**Comment by shirosaidev** [comment]
@owenmurr I pushed some more updates today, please pull and let me know if any issues with crawlbot continuous scanner (-B).
